name: CI
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Execute Unit Tests
        run: bash ./tests/start.sh "./tests/"
        shell: bash
